spring:
  application:
    name: Spring Cloud Gateway
  cloud:
    gateway:
      enabled: true #开启或关闭gateway
      routes:
      - id: add_request_header_route
        uri: http://localhost:9001
        predicates:
        - Path=/greeting
        filters:
        - AddRequestHeader=Shape, Circle
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/failure

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: false #开启或关闭eureka客户端

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"